DATETIME_FORMAT:
    date: '%Y-%m-%d'
    datetime: '%Y-%m-%dT%H%M%S'
    time: '%H-%M-%S'
FILESYSTEM_OPTIONS:
    ignore:
    - '*.swp'
    - '*/.*'
    sanitize_filename: true
    sanitize_strict: false
FILETAGS_OPTIONS:
    between_tag_separator: ' '
    filename_tag_separator: ' -- '
NAME_TEMPLATES:
    default_book: '{publisher} {title} {edition} - {author} {datetime}.{extension}'
    default_document: '{title} - {author} {datetime}.{extension}'
    default_photo: '{datetime} {description} -- {tags}.{extension}'
RULES:
-   CONDITIONS:
        filesystem.basename.extension: pdf
        filesystem.basename.full: gmail.pdf
        filesystem.contents.mime_type: application/pdf
    DATA_SOURCES:
        datetime: extractor.metadata.exiftool.PDF:CreateDate
        extension: filesystem.basename.extension
        title: filesystem.basename.prefix
    NAME_FORMAT: '{datetime} {title}.{extension}'
    description: test_files Gmail print-to-pdf
    exact_match: true
    ranking_bias: null
-   CONDITIONS:
        filesystem.basename.full: smulan.jpg
        filesystem.contents.mime_type: image/jpeg
    DATA_SOURCES:
        datetime: extractor.metadata.exiftool.EXIF:DateTimeOriginal
        description: plugin.microsoft_vision.caption
        extension: filesystem.basename.extension
    NAME_FORMAT: '{datetime} {description}.{extension}'
    description: test_files smulan.jpg
    exact_match: true
    ranking_bias: 1
-   CONDITIONS:
        filesystem.basename.full: simplest_pdf.md.pdf
    DATA_SOURCES:
        extension: filesystem.basename.extension
    NAME_FORMAT: simplest_pdf.md.{extension}
    description: test_files simplest_pdf.md.pdf
    exact_match: true
    ranking_bias: 1
autonameow_version: v0.4.5
