DATETIME_FORMAT:
    date: '%Y-%m-%d'
    datetime: '%Y-%m-%dT%H%M%S'
    time: '%H-%M-%S'
FILESYSTEM_OPTIONS:
    ignore:
    - '*.swp'
    - '*/.*'
    sanitize_filename: true
    sanitize_strict: false
RULES:
-   CONDITIONS:
        extractor.filesystem.xplat.contents.mime_type: '*/*'
    DATA_SOURCES:
        extension: extractor.filesystem.xplat.contents.mime_type
        title: extractor.filesystem.xplat.basename.prefix
    NAME_FORMAT: '{title}.{extension}'
    description: Fix incorrect extensions
    exact_match: false
    ranking_bias: 0.01
autonameow_version: v0.4.7
