@startuml
' ____________________________________________________________________________
' ____ CONFIGURATION OPTIONS __________________________________________________
' debug flag creates a 'svek.dot' and 'svek.svg' file in ~/
!pragma svek_trace on

' package graphical style
skinparam packageStyle folder

' don't use symbols to indicate visibility
' skinparam classAttributeIconsize 0


' ____________________________________________________________________________
' ____ CLASS DEFINITIONS ______________________________________________________
package autonameow.analyze {
    class AnalyzerBase {
        fileObject:FileObject
        --
        +toString():String
    }

    class ImageAnalyzer {
        fileObject:FileObject
    }

    class PdfAnalyzer {
        fileObject:FileObject
    }

    class VideoAnalyzer {
        fileObject:FileObject
    }
}


' ____________________________________________________________________________
' ____ RELATIONS BETWEEN CLASSES _____________________________________________
' <|--      extension
' *--       composition
' o--       aggregation

' COMPOSITION
' Figure <.. Vertex2D
' SimpleFigure <.. Vertex2D
Figure       "1" *-- "many" Vertex2D : contains
SimpleFigure "1" *-- "1"    Vertex2D : contains

' INHERITANCE
AnalyzerBase <|-- ImageAnalyzer
AnalyzerBase <|-- PdfAnalyzer
AnalyzerBase <|-- VideoAnalyzer

' IMPLEMENT INTERFACES
Movable <.. Figure
Rotatable <.. Figure
Scalable <.. Figure

Movable <.. SimpleFigure
Scalable <.. SimpleFigure

' INHERITANCE
Figure <|-- Line
Figure <|-- Triangle
Figure <|-- Rectangle
Figure <|-- Square




@enduml
