COMPATIBILITY:
    autonameow_version: v0.4.9
CUSTOM_POST_PROCESSING:
    lowercase_filename: false
    replacements:
        -{2,}: '-'
        \.{2,}: .
        _{2,}: _
    sanitize_filename: true
    sanitize_strict: false
    uppercase_filename: false
DATETIME_FORMAT:
    date: '%Y-%m-%d'
    datetime: '%Y-%m-%dT%H%M%S'
    time: '%H-%M-%S'
FILESYSTEM_OPTIONS:
    ignore:
    - '*.swp'
    - '*/.*'
FILETAGS_OPTIONS:
    between_tag_separator: ' '
    filename_tag_separator: ' -- '
NAME_TEMPLATES:
    default_book: '{publisher} {title} {edition} - {author} {date}.{extension}'
    default_document: '{title} - {author} {datetime}.{extension}'
    default_photo: '{datetime} {description} -- {tags}.{extension}'
NAME_TEMPLATE_FIELDS:
    publisher:
        candidates:
            FeedBooks:
            - This book is brought to you by Feedbooks
            - http://www.feedbooks.com
            ProjectGutenberg:
            - Project Gutenberg
            - www.gutenberg.net
PERSISTENCE:
    cache_directory: null
    history_directory: null
RULES:
    Sample Entry for E-books:
        CONDITIONS:
            extractor.filesystem.xplat.contents.mime_type:
            - application/pdf
            - application/epub+zip
            - image/vnd.djvu
            extractor.filesystem.xplat.pathname.full: .*book.*
        DATA_SOURCES:
            author: analyzer.ebook.author
            date: analyzer.ebook.date
            edition: analyzer.ebook.edition
            extension: extractor.filesystem.xplat.contents.mime_type
            publisher: analyzer.ebook.publisher
            title: analyzer.ebook.title
        NAME_FORMAT: default_book
        exact_match: true
        ranking_bias: 0.1
    Sample Entry for Photos with strict rules:
        CONDITIONS:
            extractor.filesystem.xplat.basename.extension: jpg
            extractor.filesystem.xplat.basename.full: DCIM*
            extractor.filesystem.xplat.contents.mime_type: image/jpeg
            extractor.filesystem.xplat.pathname.full: ~/Pictures/incoming
            extractor.metadata.exiftool.EXIF:DateTimeOriginal: Defined
        DATA_SOURCES:
            datetime:
            - extractor.metadata.exiftool.EXIF:DateTimeOriginal
            - extractor.metadata.exiftool.EXIF:DateTimeDigitized
            - extractor.metadata.exiftool.EXIF:CreateDate
            description: plugin.microsoft_vision.caption
            extension: extractor.filesystem.xplat.basename.extension
            tags: plugin.microsoft_vision.tags
        NAME_FORMAT: '{datetime} {description} -- {tags}.{extension}'
        exact_match: true
        ranking_bias: 1
    test_files Gmail print-to-pdf:
        CONDITIONS:
            extractor.filesystem.xplat.basename.extension: pdf
            extractor.filesystem.xplat.basename.full: gmail.pdf
            extractor.filesystem.xplat.contents.mime_type: application/pdf
        DATA_SOURCES:
            datetime: extractor.metadata.exiftool.PDF:CreateDate
            extension: extractor.filesystem.xplat.basename.extension
            title: extractor.filesystem.xplat.basename.prefix
        NAME_FORMAT: '{datetime} {title}.{extension}'
        exact_match: true
        ranking_bias: null
    test_files simplest_pdf.md.pdf:
        CONDITIONS:
            extractor.filesystem.xplat.basename.full: simplest_pdf.md.pdf
        DATA_SOURCES:
            extension: extractor.filesystem.xplat.basename.extension
        NAME_FORMAT: simplest_pdf.md.{extension}
        exact_match: true
        ranking_bias: 1
    test_files smulan.jpg:
        CONDITIONS:
            extractor.filesystem.xplat.basename.full: smulan.jpg
            extractor.filesystem.xplat.contents.mime_type: image/jpeg
        DATA_SOURCES:
            datetime: extractor.metadata.exiftool.EXIF:DateTimeOriginal
            description: plugin.microsoft_vision.caption
            extension: extractor.filesystem.xplat.basename.extension
        NAME_FORMAT: '{datetime} {description}.{extension}'
        exact_match: true
        ranking_bias: 1
