FILE_RULES:
- CONDITIONS:
    contents:
      mime_type: null
    filename:
      basename: null
      extension: null
      pathname: null
    metadata:
      exif:
        camera-model: null
        datetimeoriginal: null
  DATA_SOURCES:
    author: null
    datetime: null
    description: null
    extension: filename.extension
    publisher: null
    title: null
  NAME_TEMPLATE: default_document
  _description: First Entry in the Default Configuration
  _exact_match: false
  _weight: null
- CONDITIONS:
    contents:
      metadata: exif.datetimeoriginal
      mime_type: image/jpeg
    filename:
      basename: DCIM*
      extension: jpg
      pathname: ~/Pictures/incoming
  DATA_SOURCES:
    author: null
    datetime:
    - metadata.exif.datetimeoriginal
    - metadata.exif.datetimedigitized
    - metadata.exif.createdate
    description: plugin.microsoftvision.caption
    extension: filename.extension
    publisher: null
    tags: plugin.microsoftvision.tags
    title: null
  NAME_FORMAT: '{datetime} {description} -- {tags}.{extension}'
  _description: Sample Entry for Photos with strict rules
  _exact_match: true
  _weight: 1
- CONDITIONS:
    contents:
      metadata: metadata.XMP-dc.***
      mime_type: application/epub+zip
    filename:
      basename: null
      extension: epub
      pathname: null
  DATA_SOURCES:
    author:
    - metadata.XMP-dc.Creator
    - metadata.XMP-dc.CreatorFile-as
    datetime:
    - metadata.XMP-dc.PublicationDate
    - metadata.XMP-dc.Date
    description: null
    edition: null
    extension: filename.extension
    publisher: metadata.XMP-dc.Publisher
    tags: null
    title: metadata.XMP-dc.Title
  NAME_FORMAT: ''
  NAME_TEMPLATE: default_book
  _description: Sample Entry for EPUB e-books
  _exact_match: true
  _weight: 1
- CONDITIONS:
    contents:
      metadata: metadata.MOBI.***
      mime_type: application/x-mobipocket-ebook
    filename:
      basename: null
      extension:
      - mobi
      pathname: null
  DATA_SOURCES:
    author: metadata.MOBI.Author
    datetime:
    - metadata.MOBI.PublishDate
    description:
    - metadata.MOBI.Description
    - metadata.MOBI.Subject
    extension: filename.extension
    publisher: metadata.MOBI.Publisher
    tags: null
    title:
    - metadata.MOBI.BookName
    - metadata.MOBI.UpdatedTitle
  NAME_FORMAT: '{publisher} {title} {edition} - {author} {date}.{extension}'
  NAME_TEMPLATE: null
  _description: Sample Entry for MOBI e-books
  _exact_match: true
  _weight: 1
NAME_TEMPLATES:
  default_book: '{publisher} {title} {edition} - {author} {date}.{extension}'
  default_document: '{title} - {author} {datetime}.{extension}'
  default_photo: '{datetime} {description} -- {tags}.{extension}'
name_datetime_format:
  date: '%Y-%m-%d'
  datetime: '%Y-%m-%dT%H%M%S'
  time: '%H-%M-%S'
