DATETIME_FORMAT:
    date: '%Y-%m-%d'
    datetime: '%Y-%m-%dT%H%M%S'
    time: '%H-%M-%S'
FILETAGS_OPTIONS:
    between_tag_separator: ' '
    filename_tag_separator: ' -- '
FILE_RULES:
-   CONDITIONS:
        contents.mime_type: application/pdf
        filesystem.basename.extension: pdf
        filesystem.basename.full: gmail.pdf
    DATA_SOURCES:
        datetime: metadata.exiftool.PDF:CreateDate
        extension: filesystem.basename.extension
        title: filesystem.basename.prefix
    NAME_FORMAT: '{datetime} {title}.{extension}'
    description: test_files Gmail print-to-pdf
    exact_match: true
    weight: null
-   CONDITIONS:
        contents.mime_type: image/jpeg
        filesystem.basename.full: smulan.jpg
    DATA_SOURCES:
        datetime: metadata.exiftool.EXIF:DateTimeOriginal
        description: plugin.microsoft_vision.caption
        extension: filesystem.basename.extension
    NAME_FORMAT: '{datetime} {description}.{extension}'
    description: test_files smulan.jpg
    exact_match: true
    weight: 1
-   CONDITIONS:
        filesystem.basename.full: simplest_pdf.md.pdf
    DATA_SOURCES:
        extension: filesystem.basename.extension
    NAME_FORMAT: simplest_pdf.md.{extension}
    description: test_files simplest_pdf.md.pdf
    exact_match: true
    weight: 1
-   CONDITIONS:
        contents.mime_type: image/jpeg
        filesystem.basename.extension: jpg
        filesystem.basename.full: DCIM*
        filesystem.pathname.full: ~/Pictures/incoming
        metadata.exiftool.EXIF:DateTimeOriginal: Defined
    DATA_SOURCES:
        author: null
        datetime:
        - metadata.exiftool.EXIF:DateTimeOriginal
        - metadata.exiftool.EXIF:DateTimeDigitized
        - metadata.exiftool.EXIF:CreateDate
        description: plugin.microsoft_vision.caption
        extension: filesystem.basename.extension
        publisher: null
        tags: plugin.microsoft_vision.tags
        title: null
    NAME_FORMAT: '{datetime} {description} -- {tags}.{extension}'
    description: Sample Entry for Photos with strict rules
    exact_match: true
    weight: 1
-   CONDITIONS:
        contents.mime_type: application/epub+zip
        filesystem.basename.extension: epub
        filesystem.basename.full: .*
        filesystem.pathname.full: .*
        metadata.exiftool.XMP-dc:Creator: Defined
    DATA_SOURCES:
        author:
        - metadata.exiftool.XMP-dc:Creator
        - metadata.exiftool.XMP-dc:CreatorFile-as
        datetime:
        - metadata.exiftool.XMP-dc:PublicationDate
        - metadata.exiftool.XMP-dc:Date
        description: null
        edition: null
        extension: filesystem.basename.extension
        publisher: metadata.exiftool.XMP-dc:Publisher
        tags: null
        title: metadata.exiftool.XMP-dc:Title
    NAME_FORMAT: default_book
    description: Sample Entry for EPUB e-books
    exact_match: true
    weight: 1
NAME_TEMPLATES:
    default_book: '{publisher} {title} {edition} - {author} {date}.{extension}'
    default_document: '{title} - {author} {datetime}.{extension}'
    default_photo: '{datetime} {description} -- {tags}.{extension}'
autonameow_version: v0.4.4
