file_rules:
- _description: First Entry in the Default Configuration
  _exact_match: false
  _weight: null
  conditions:
    contents:
      mime_type: null
    filename:
      basename: null
      extension: null
      pathname: null
  data_sources:
    author: null
    datetime: null
    description: null
    extension: filename.extension
    publisher: null
    title: null
  name_template: default_template_name
- _description: Sample Entry for Photos with strict rules
  _exact_match: true
  _weight: 1
  conditions:
    contents:
      metadata: exif.datetimeoriginal
      mime_type: image/jpeg
    filename:
      basename: DCIM*
      extension: jpg
      pathname: ~/Pictures/incoming
  data_sources:
    author: null
    datetime:
    - metadata.exif.datetimeoriginal
    - metadata.exif.datetimedigitized
    - metadata.exif.createdate
    description: plugin.microsoftvision.caption
    extension: filename.extension
    publisher: null
    tags: plugin.microsoftvision.tags
    title: null
  name_format: '%(datetime(%Y-%m-%dT%H%M%S))s %(description)s -- %(tags)s.%(extension)s'
- _description: Sample Entry for EPUB e-books
  _exact_match: true
  _weight: 1
  conditions:
    contents:
      metadata: metadata.XMP-dc.***
      mime_type: application/epub+zip
    filename:
      basename: null
      extension: epub
      pathname: null
  data_sources:
    author:
    - metadata.XMP-dc.Creator
    - metadata.XMP-dc.CreatorFile-as
    datetime:
    - metadata.XMP-dc.PublicationDate
    - metadata.XMP-dc.Date
    description: null
    edition: null
    extension: filename.extension
    publisher: metadata.XMP-dc.Publisher
    tags: null
    title: metadata.XMP-dc.Title
  name_format: ''
  name_template: default_ebook_name
- _description: Sample Entry for MOBI e-books
  _exact_match: true
  _weight: 1
  conditions:
    contents:
      metadata: metadata.MOBI.***
      mime_type: application/x-mobipocket-ebook
    filename:
      basename: null
      extension:
      - mobi
      pathname: null
  data_sources:
    author: metadata.MOBI.Author
    datetime:
    - metadata.MOBI.PublishDate
    description:
    - metadata.MOBI.Description
    - metadata.MOBI.Subject
    extension: filename.extension
    publisher: metadata.MOBI.Publisher
    tags: null
    title:
    - metadata.MOBI.BookName
    - metadata.MOBI.UpdatedTitle
  name_format: null
  name_template: default_ebook_name
name_templates:
- _description: First name template in the Default Configuration
  _name: default_template_name
  name_format: '%(title)s - %(author)s %(datetime)s.%(extension)s'
- _description: Ebook name template in the Default Configuration
  _name: default_ebook_name
  name_format: '%(publisher)s %(title)s %(edition)s - %(author)s %(year)s.%(extension)s'
