DATETIME_FORMAT:
    date: '%Y-%m-%d'
    datetime: '%Y-%m-%dT%H%M%S'
    time: '%H-%M-%S'
FILESYSTEM_OPTIONS:
    sanitize_filename: true
    sanitize_strict: false
FILETAGS_OPTIONS:
    between_tag_separator: ' '
    filename_tag_separator: ' -- '
RULES:
-   CONDITIONS:
        analysis.filetags.follows_filetags_convention: true
        filesystem.basename.extension: '(jpg|png)'
        filesystem.contents.mime_type: 'image/*'
    DATA_SOURCES:
        datetime: analysis.filetags.datetime
        extension: filesystem.contents.mime_type
        description: analysis.filetags.description
        tags: analysis.filetags.tags
    NAME_FORMAT: '{datetime} {description} -- {tags}.{extension}'
    description: Filetags cleanup
    exact_match: true
    ranking_bias: 0.1
-   CONDITIONS:
        filesystem.basename.extension: pdf
        filesystem.basename.full: (Apress|DIY|Wiley|Springer|NoStarchPress) .* - (\S+ [A-Z]\.)+ \d{4}.pdf
        filesystem.contents.mime_type: application/pdf
    DATA_SOURCES:
        extension: filesystem.basename.extension
        title: filesystem.basename.prefix
        # description: contents.visual.ocr_text
    NAME_FORMAT: '{title} {description}.{extension}'
    description: PDF e-books (strict)
    exact_match: true
    ranking_bias: 0.8
-   CONDITIONS:
        filesystem.contents.mime_type: '*/*'
    DATA_SOURCES:
        extension: filesystem.contents.mime_type
        title: filesystem.basename.prefix
    NAME_FORMAT: '{title}.{extension}'
    description: Fix incorrect extensions
    exact_match: false
    ranking_bias: 0.01
-   CONDITIONS:
        filesystem.basename.extension: pdf
        filesystem.basename.full: gmail.pdf
        filesystem.contents.mime_type: application/pdf
    DATA_SOURCES:
        datetime: metadata.exiftool.PDF:CreateDate
        extension: filesystem.basename.extension
        title: filesystem.basename.prefix
    NAME_FORMAT: '{datetime} {title}.{extension}'
    description: test_files Gmail print-to-pdf
    exact_match: true
    ranking_bias: null
-   CONDITIONS:
        filesystem.basename.full: smulan.jpg
        filesystem.contents.mime_type: image/jpeg
    DATA_SOURCES:
        datetime: metadata.exiftool.EXIF:DateTimeOriginal
        description: plugin.microsoft_vision.caption
        extension: filesystem.basename.extension
    NAME_FORMAT: '{datetime} {description}.{extension}'
    description: test_files smulan.jpg
    exact_match: true
    ranking_bias: 1
-   CONDITIONS:
        filesystem.basename.full: simplest_pdf.md.pdf
    DATA_SOURCES:
        extension: filesystem.basename.extension
    NAME_FORMAT: 'simplest_pdf.md.{extension}'
    description: test_files simplest_pdf.md.pdf
    exact_match: true
    ranking_bias: 1
-   CONDITIONS:
        filesystem.basename.extension: jpg
        filesystem.basename.full: DCIM*
        filesystem.contents.mime_type: image/jpeg
        filesystem.pathname.full: ~/Pictures/incoming
        metadata.exiftool.EXIF:DateTimeOriginal: Defined
    DATA_SOURCES:
        datetime:
        - metadata.exiftool.EXIF:DateTimeOriginal
        - metadata.exiftool.EXIF:DateTimeDigitized
        - metadata.exiftool.EXIF:CreateDate
        description: plugin.microsoft_vision.caption
        extension: filesystem.basename.extension
        tags: plugin.microsoft_vision.tags
    NAME_FORMAT: '{datetime} {description} -- {tags}.{extension}'
    description: Sample Entry for Photos with strict rules
    exact_match: true
    ranking_bias: 1
-   CONDITIONS:
        filesystem.basename.extension: epub
        filesystem.basename.full: .*
        filesystem.contents.mime_type: application/epub+zip
        filesystem.pathname.full: .*
        metadata.exiftool.XMP-dc:Creator: Defined
    DATA_SOURCES:
        author:
        - metadata.exiftool.XMP-dc:Creator
        - metadata.exiftool.XMP-dc:CreatorFile-as
        datetime:
        - metadata.exiftool.XMP-dc:PublicationDate
        - metadata.exiftool.XMP-dc:Date
        edition: null
        extension: filesystem.basename.extension
        publisher: metadata.exiftool.XMP-dc:Publisher
        title: metadata.exiftool.XMP-dc:Title
    NAME_FORMAT: default_book
    description: Sample Entry for EPUB e-books
    exact_match: true
    ranking_bias: 1
NAME_TEMPLATES:
    default_book: '{publisher} {title} {edition} - {author} {datetime}.{extension}'
    default_document: '{title} - {author} {datetime}.{extension}'
    default_photo: '{datetime} {description} -- {tags}.{extension}'
autonameow_version: v0.4.5
