file_rules:
- _description: First Entry in the Default Configuration
  _exact_match: false
  _weight: null
  conditions:
    contents:
      mime_type: null
    filename:
      basename: null
      extension: null
      pathname: null
  data_sources:
    author: null
    datetime: null
    description: null
    extension: filename.extension
    publisher: null
    title: null
  name_template: default_template_name
name_templates:
- _description: First name template in the Default Configuration
  _name: default_template_name
  format: '[datetime(%Y-%m-%dT%H%M%S)] [description].[ext]'
